# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ff62ff73a5fa7c1da4a355b6fa4680ea9e65870acf6dc3fd70acd630c75d308a11303baa0c29926caa32b57b3bdff124090bddfea2706da09fd9080d40da35e

test:
  secret_key_base: 1113c5a7fc3c2bf2c6703c76828e6043518ca030fefdd0959a43901ddb8103b567e34af044c4e1445e4bace5574b7ea40ed9f47fb077cc65f6761d04999eaab0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
